# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build a new version"
  lane :build do |options|
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => options[:storefile],
        "android.injected.signing.store.password" => options[:storepass],
        "android.injected.signing.key.alias" => options[:keyalias],
        "android.injected.signing.key.password" => options[:keypass],
      }
    )
  end

  desc "Deploy the new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: "production",
      skip_upload_metadata: "true",
      skip_upload_images: "false",
      skip_upload_screenshots: "true",
      apk: "./app/build/outputs/apk/release/app-release.apk",
      validate_only: "false",
    )
  end
end
